version: "3"

services:

  donas-admin:
    container_name: donas-admin
    build:
      context: .
      dockerfile: ./apps-donas/admin/Dockerfile
    # command: ./bin/rails server -p 3000 -b 0.0.0.0
    restart: always
    environment:
      REDISCLOUD_URL: redis://redis
      DATABASE_URL: postgres://postgres@db/development
    volumes:
      - .:/myapp
    links:
    - db
    - redis
    ports:
      - 3000:3000
    networks:
      - app_network

  donas-api:
    container_name: donas-api
    build:
      context: .
      dockerfile: ./donas-apps/api/Dockerfile
    restart: always
    environment:
      REDISCLOUD_URL: redis://redis
      DATABASE_URL: postgres://postgres@db/development
    volumes:
      - .:/myapp
    links:
    - db
    - redis
    ports:
      - 3001:3000
    networks:
      - app_network

  db:
    image: postgres:13.11
    ports:
    - "5432:5432"

  redis:
    image: redis
    ports:
    - "6379:6379"

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
