apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: dona-civo-turbo-yarn-docker
build:
  artifacts:
    - image: donas-admin
      context: apps-donas/admin
      docker:
        dockerfile: Dockerfile
    - image: donas-api
      context: apps-donas/api
      docker:
        dockerfile: Dockerfile
manifests:
  kustomize:
    paths:
      - apps-donas/admin/k8s
profiles:
  - name: k8s
    manifests:
      kustomize:
        paths:
          - apps-donas/api/k8s
