apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    
    
  
  labels:
    io.kompose.service: donas-admin
  name: donas-admin
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: donas-admin
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        
        
      
      labels:
        io.kompose.network/app-network: "true"
        io.kompose.service: donas-admin
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: postgres://postgres@db/development
            - name: REDISCLOUD_URL
              value: redis://redis
          image: donas-admin
          name: donas-admin
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /myapp
              name: donas-admin-claim0
      restartPolicy: Always
      volumes:
        - name: donas-admin-claim0
          persistentVolumeClaim:
            claimName: donas-admin-claim0
status: {}
