apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker-compose.yml
    
  
  labels:
    io.kompose.service: donas-admin
  name: donas-admin
  namespace: default
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: donas-admin
status:
  loadBalancer: {}
