apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  
  labels:
    io.kompose.service: donas-admin-claim0
  name: donas-admin-claim0
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
