apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    
    
  
  labels:
    io.kompose.service: redis
  name: redis
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  strategy: {}
  template:
    metadata:
      annotations:
        
        
      
      labels:
        io.kompose.network/dona-civo-turbo-yarn-docker-default: "true"
        io.kompose.service: redis
    spec:
      containers:
        - image: redis
          name: redis
          ports:
            - containerPort: 6379
              hostPort: 6379
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
