# https://kubernetes.io/docs/concepts/configuration/secret/

apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: bW9uZ291c2VyCg== # mongouser
  mongo-password: bW9uZ29wYXNzd29yZAo= # mongopasswrod
